# Generated by Django 5.2.6 on 2025-09-22 02:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='記事のURL', unique=True)),
                ('title', models.CharField(blank=True, help_text='記事のタイトル', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='最後に順位をチェックした日時', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'アクティブ'), ('INACTIVE', '非アクティブ'), ('ARCHIVED', 'アーカイブ済み')], default='ACTIVE', help_text='記事の状態', max_length=10)),
                ('domain', models.ForeignKey(help_text='所属するドメイン', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='search.domain')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('domain', 'url')},
            },
        ),
    ]
