# Generated by Django 5.2.6 on 2025-09-22 05:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERPResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_engine', models.CharField(choices=[('GOOGLE', 'Google'), ('BING', 'Bing')], help_text='検索エンジン', max_length=10)),
                ('rank', models.PositiveIntegerField(help_text='検索順位')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='計測日時')),
                ('article', models.ForeignKey(help_text='対象の記事', on_delete=django.db.models.deletion.CASCADE, related_name='serp_results', to='search.article')),
            ],
            options={
                'ordering': ['-checked_at'],
                'unique_together': {('article', 'search_engine', 'checked_at')},
            },
        ),
    ]
