### =================================
### Domain APIs
### =================================

# 変数定義: テスト対象のドメインID
# 最初にPOSTで作成したドメインのIDに書き換えてください
@domain_id = 4

###
### [GET] 全てのドメイン一覧を取得
GET http://localhost:8000/api/domains/

###
### [POST] 新しいドメインを作成
POST http://localhost:8000/api/domains/
Content-Type: application/json

{
    "url": "example.com"
}

###
### [GET] 特定のドメインの詳細を取得
GET http://localhost:8000/api/domains/{{domain_id}}/

###
### [PUT] 特定のドメインを更新
PUT http://localhost:8000/api/domains/{{domain_id}}/
Content-Type: application/json

{
    "url": "updated-example.com"
}

###
### [DELETE] 特定のドメインを削除
DELETE http://localhost:8000/api/domains/{{domain_id}}/


### =================================
### Article APIs
### =================================

# 変数定義: テスト対象の記事ID (UUID)
# 最初にPOSTで作成した記事のIDに書き換えてください
@article_id = 9f6ed77c-f9f1-4920-b0a1-164fac0559ae

###
### [GET] 全ての記事一覧を取得
GET http://localhost:8000/api/articles/

###
### [POST] 新しい記事を作成
# 上で定義した @domain_id を使います
POST http://localhost:8000/api/articles/
Content-Type: application/json

{
    "domain": {{domain_id}},
    "url": "https://example.com/article01",
    "title": "Article01"
}

###
### [GET] 特定の記事の詳細を取得
GET http://localhost:8000/api/articles/{{article_id}}/

###
### [PATCH] 特定の記事を部分更新
PATCH http://localhost:8000/api/articles/{{article_id}}/
Content-Type: application/json

{
    "title": "My Awesome Article (Updated)"
}

###
### [DELETE] 特定の記事を削除
DELETE http://localhost:8000/api/articles/{{article_id}}/

### =================================
### SERPResult APIs
### =================================

# 変数定義: テスト対象のSERPResult ID (UUID)
@serp_result_id = 262f0d21-0ed5-4e0e-a0f4-cc638b813472

###
### [GET] 全ての検索結果一覧を取得
GET http://localhost:8000/api/serp-results/

###
### [POST] 新しい検索結果を作成
POST http://localhost:8000/api/serp-results/
Content-Type: application/json

{
    "article": "{{article_id}}",
    "search_engine": "GOOGLE",
    "rank": 10
}

###
### [GET] 特定の検索結果の詳細を取得
GET http://localhost:8000/api/serp-results/{{serp_result_id}}/

###
### [PATCH] 特定の検索結果を部分更新
PATCH http://localhost:8000/api/serp-results/{{serp_result_id}}/
Content-Type: application/json

{
    "rank": 5
}

###
### [DELETE] 特定の検索結果を削除
DELETE http://localhost:8000/api/serp-results/{{serp_result_id}}/
